
#name: Build and Deploy
# on:
#   push:
#     branches:
#     - master
#   pull_request:
#     branches:
#     - master
# permissions:
#   contents: write
# jobs:
#   build-and-deploy:
#     concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
#     runs-on: ubuntu-latest
#     steps:
#       - name: Yarn Setup
#         # You may pin to the exact commit or the version.
#         # uses: DerYeger/yarn-setup-action@f55be5383ea94f5eb25b20aee609af4603a68dde
#         uses: DerYeger/yarn-setup-action@v1.0.1
#         with:
#           # The version of Node.js that will be used
#           node-version: 16
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v3

#       - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
#         run: |
#           yarn
#           yarn build

#       - name: Deploy ğŸš€
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: docs # The folder the action should deploy.
